---
title: "Development/Docker: Compose"
format:
  html:
    toc: true
    html-math-method: katex
    code-fold: true
knitr:
  opts_chunk:
    echo: true
---


In this tutorial, I demonstrate how to set up and deploy a **custom docker container** with [**docker-compose**](https://docs.docker.com/compose).
This is intended to be a rather general test case, serving for later configuration of more specific container solutions.
I follow other tutorials available online, and try to capture their essence for an INBO-context.


Originally, this covers the steps to be executed on an (arch) linux computer or within a WSL.
On Windows, installation is different, yet there should be a linux-like terminal in the `docker desktop` app which would allow you to run the same commands.

I will later attempt to reproduce the steps on windows.



__References:__

- <https://jsta.github.io/r-docker-tutorial/02-Launching-Docker.html>
-   <https://medium.com/@geeekfa/docker-compose-setup-for-a-python-flask-api-with-nginx-reverse-proxy-b9be09d9db9b>
- <https://testdriven.io/blog/dockerizing-flask-with-postgres-gunicorn-and-nginx>


# Installation

The installation procedure [is documented here](https://docs.docker.com/compose/install).

Docker compose comes with the *Docker Desktop* app.
That app is probably trivial and hardly worth a tutorial.
Alternatively, you can install it as a terminal tool.


```{sh}
sudo apt update && sudo apt install docker docker-compose # debian-based
# sudo pacman -Sy docker docker-compose # arch linux
```


For users to be able to use docker, they must be in the "docker" group.
(Insert your username at `<your-username>`.)

```{sh}
sudo usermod -a -G docker <your-username>
```

For this change to take effect, log off en in again and restart of the docker service (see below).


Containers are managed by a system task ("service") which needs to be started.
Your system can start and stop that service automatically, by using `systemctl enable <...>`.  
However, due to [diverse](https://docs.docker.com/engine/security) [security](https://github.com/moby/moby/issues/9976) [pitfalls](https://snyk.io/blog/top-ten-most-popular-docker-images-each-contain-at-least-30-vulnerabilities), it is good practice to not keep it activated permanently on your system.


On a `systemd` system, you can start and stop docker on demand via the following commands (those will ask you for `sudo` authentification if necessary).

```{sh}
systemctl start docker

systemctl status docker # check status

systemctl stop docker.socket
systemctl stop docker.service
```


You can check the docker installation by confirming the version at which the service is running.

```{sh}
docker --version
```


# Existing Containers

## rationale

Docker is about working in containers, if you like that.
You can think of this as living in a ["tiny home", or "mobile home"](https://parametric-architecture.com/tiny-house-movement). 
Let's call it a fancy caravan.

If you do not have the cash to build your own home, you can of course use someone elses'.


## example

For example[^1], there are docker images with [rstudio server](https://posit.co/download/rstudio-server) pre-installed: 

- <https://hub.docker.com/r/rocker/rstudio>

[^1]: I mostly follow [this tutorial](https://jsta.github.io/r-docker-tutorial/02-Launching-Docker.html).


Execute the following script.
If it does not find the resources locally, docker will download and extract the image from dockerhub[^2].

[^2]: Just like "github" is a server service to store git repositories, guess what: "docker hub" is a service to store docker containers.

```{sh}
docker run --rm -p 8787:8787 -e PASSWORD=YOURNEWPASSWORD rocker/rstudio
```

The `--rm` flag makes the docker image non-permanent, i.e. disk space will be freed after you close the container.
The port specified at `-p` is the one you use to access this local container server.
The `-e` flag allows you to specify a password, but if you do not specify one, the container will provide a random password upon startup (read the terminal output).


You are now running (`run`) a `rocker/rstudio` server instance on your `localhost`, i.e. your computer.
You can access it via a browser, going to <localhost:8787>, with the username `rstudio` and your chosen password.


You can shut down the container with the keyboard shortcut `[ctrl]+[C]` (probably `[ctrl]+[Z]` on windows).


## file access

The downside of this is that your container is isolated (well... at least to a certain degree).

To store files locally, without storing the bloated container, you will have to map a virtual path on the container to a local drive on your computer.
(Linux people will be familiar with the concept of "mounting" and "linking" storage locations.)

Docker run brings the `-v` flag for this.
Suppose you have an R project you would like to work on, stored, for example, in this path:

- `/data/git/coding-club`

Then you can link this to your containers' home folder via the following command.

```{sh}
docker run --rm -p 8787:8787 -v /data/git/coding-club:/home/rstudio/coding-club rocker/rstudio
```

Again, navigate to <localhost:8787>, *et voilà*, you can access your project and store files back in your regular folders.


## limitation

This is a simple and quick way to run R and RStudio in a container.

However, there are limitations:

- You have to live with the R packages provided in the container, or otherwise install them each time you access it...
- ... unless you make you container permanent, omitting the `--rm` option. Note that this will cost considerable disk space, and will not transfer to other computers (the original purpose of docker).
- It should be kept in mind that software is best kept up to date. Occasionally re-install your docker image and R packages to get the latest packages.
- There is a performance penalty from using containers: in inaccurate laymans' terms, they emulate (parts of a) "computer" inside your computer. 


On the performance issue: I attempted this on my local laptop with matrix multiplication.

```{r}
# https://cran.r-project.org/web/packages/rbenchmark/rbenchmark.pdf
# install.packages("rbenchmark")

test <- function(){
  # test from https://prdm0.github.io/ropenblas/#installation
  m <- 1e4; n <- 1e3; k <- 3e2
  X <- matrix(rnorm(m*k), nrow=m); Y <- matrix(rnorm(n*k), ncol=n)
  X %*% Y
}

benchmark(test())
```

In the terminal:

```
    test replications elapsed relative user.self sys.self user.child sys.child
1 test()          100  22.391        1    83.961   65.291          0         0
```

In the container:

```
    test replications elapsed relative user.self sys.self user.child sys.child
1 test()          100  26.076        1   102.494   153.89          0         0
```

Now, the *good news* is that the difference is not by orders of magnitude, which indicates that docker seems to integrate the `blas` variant I installed on my computer (`blas-openblas`).

The *bad news* is that these are a little less than `-20%` performance, which is considerable.


This is just a single snapshot on a laptop. 
Feel free to systematically and scientifically repeat the tests on your own machine.


